added calendar and histogram component
js-tasks-ru/htmlcss-20210513_andrey-naumov pull request #11
Opened 2021-06-17 20:40 UTC by naumov210

added calendar and histogram component on the main page

2021-06-17 20:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-18 05:06 UTC, GSemikozov requested changes

2021-06-18 05:06 UTC, GSemikozov commented on components/card-calendar/card-calendar.css
> +.calendar__body-wrapper {
думаю, эта обертка оказалась лишней, не стоит переусложнять с обертками)

2021-06-18 05:06 UTC, GSemikozov commented on components/card-calendar/card-calendar.css
> +    padding-bottom: 114%;
если ниже убрать лишнюю обертку, то этот паддинг можно удалить

2021-06-18 05:06 UTC, GSemikozov commented on components/card-calendar/card-calendar.css
> +    font-size: 9px;
там точно сайз 9px?

2021-06-18 05:06 UTC, GSemikozov commented on components/card-calendar/card-calendar.css
> +    padding: 7%;
в процентах - заранее для адаптивности?

2021-06-18 05:06 UTC, GSemikozov commented on components/card-histogram/card-histogram.css
> +    flex: 1 0 auto;
можно было бы задать какой-то базовый flex-basis + на всякий случай min-width (в макете это 9px) если столбиков будет много либо ширина виджета будет маленькой

2021-06-18 05:06 UTC, GSemikozov commented on components/card/card.css
> +.card-grid {
то что касается внешнего оформления - а оформляем мы здесь сетку карточек через другой блок .card-grid - нужно вынести в отдельный файл стилей блока .card-grid

2021-06-18 05:06 UTC, GSemikozov commented on components/card/card.css
> +    white-space: pre;
->. `nowrap` ;)

2021-06-19 14:57 UTC, naumov210 commented on components/card-calendar/card-calendar.css
> +.calendar__body-wrapper {
Убрал!

2021-06-19 14:58 UTC, naumov210 commented on components/card-calendar/card-calendar.css
> +    padding-bottom: 114%;
Удалил!

2021-06-19 16:47 UTC, naumov210 commented on components/card-calendar/card-calendar.css
> +    font-size: 9px;
В готовом проекте - да. В стайл-гайде дни недели 14px, а числа16px. Но это слишком много. элементы слишком большие получаются - дни недели прижимаются слишком плотно. 
Оставил 9px.

2021-06-19 16:48 UTC, naumov210 commented on components/card-calendar/card-calendar.css
> +    padding: 7%;
да, после апрува, сделаю сетку для планшета и мобильника

2021-06-19 17:18 UTC, naumov210 commented on components/card-histogram/card-histogram.css
> +    flex: 1 0 auto;
Здесь сложности. Добавил flex-basis в px и в % и добавил min-width: 9px. всё ломается - столбики переполняют контейнер и выпадают из него при уменьшении вьюпорта. Похоже я не знаю как это решить !

2021-06-19 17:23 UTC, naumov210 commented on components/card/card.css
> +.card-grid {
создал card-grid.css в папке компонента .card
или нужно в компонентах создать отдельную папку card-grid для card-grid.css и поместить стили в неё ?

2021-06-19 17:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-19 18:35 UTC, GSemikozov commented on components/card-calendar/card-calendar.css
> +    font-size: 9px;
обычно нужно придерживаться стайл гайда по максимуму, но - хорошо, допустимо уменьшить.

2021-06-19 18:36 UTC, GSemikozov commented on components/card-histogram/card-histogram.css
> +    flex: 1 0 auto;
тут нужно смотреть живьем - есть возможность перенести стили и разметку компонента в codepen?

2021-06-19 18:37 UTC, GSemikozov commented on components/card/card.css
> +.card-grid {
так нормально, главное - что эти стили вспомогательные и актуально только для одного примера в хтмл файле ДЗ, так что не особо важно где и как мы разместим этот файл

2021-06-22 13:29 UTC, GSemikozov commented on components/card-histogram/card-histogram.css
> +    flex: 1 0 auto;
вроде пофиксили?)

2021-06-22 15:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-22 20:55 UTC, GSemikozov approved these changes

2021-06-22 20:55 UTC, merged