Complited the task calendar
js-tasks-ru/htmlcss-20210513_andrey-naumov pull request #9
Opened 2021-06-08 20:20 UTC by naumov210

Added the task-calendar solution

2021-06-08 20:21 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-09 07:11 UTC, GSemikozov requested changes

2021-06-09 07:11 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    grid-template-rows: repeat(6, 1fr);
мы именно по колонкам выстаиваем layout, rows template задавать явно - нет нужды, можем убрать

2021-06-09 11:17 UTC, naumov210 commented on 05-lection3/03-calendar/calendar.css
> +    grid-template-rows: repeat(6, 1fr);
Я так и знал. Ещё и думал не описывать ряды. Ок !

2021-06-09 15:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-09 15:58 UTC, GSemikozov approved these changes

2021-06-09 15:58 UTC, merged